/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.roytuts.junit.setup.gradle.maven;

public class Library {
	
    public boolean someLibraryMethod() {
        return true;
    }
    
}
